{% set name = "asyncpg" %}
{% set version = "0.31.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c989386c83940bfbd787180f2b1519415e2d3d6277a70d9d0f0145ac73500735

build:
  number: 0
  script: {{ PYTHON }} -m pip install --no-deps --no-build-isolation .
  skip: true  # [py<390]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - setuptools >=77.0.3
    - cython >=3.2.1,<4.0.0
  run:
    - python
    - async-timeout >=4.0.3  # [py<311]
    - async_timeout >=4.0.3  # [py<311]

test:
  imports:
    - asyncpg
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/MagicStack/asyncpg
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: A fast PostgreSQL Database Client Library for Python/asyncio.
  description: |
    asyncpg is a database interface library designed specifically for
    PostgreSQL and Python/asyncio. asyncpg is an efficient, clean
    implementation of PostgreSQL server binary protocol for use with Python's
    asyncio framework.
  doc_url: https://magicstack.github.io/asyncpg
  dev_url: https://github.com/MagicStack/asyncpg

extra:
  recipe-maintainers:
    - nehaljwani
    - xhochy
